php_sample.lo: /home/php2c/ext/php_sample.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/php2c/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/php2c/ext/php_sample.c -o php_sample.lo 
$(phplibdir)/sample.la: ./sample.la
	$(LIBTOOL) --mode=install cp ./sample.la $(phplibdir)

./sample.la: $(shared_objects_sample) $(SAMPLE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_sample) $(SAMPLE_SHARED_LIBADD)

